import json

with open("crates/ui/src/theme/default-theme.json", "r") as f:
    data = json.load(f)

# Update Light Theme (Zinc)
light_colors = {
    "background": "#ffffff",
    "foreground": "#09090b",
    "border": "#e4e4e7",
    "ring": "#18181b",
    "input.border": "#e4e4e7",
    "muted.background": "#f4f4f5",
    "muted.foreground": "#71717a",
    "secondary.background": "#f4f4f5",
    "secondary.foreground": "#18181b",
    "secondary.hover.background": "#e4e4e7",
    "secondary.active.background": "#d4d4d8",
    "primary.background": "#18181b",
    "primary.foreground": "#fafafa",
    "primary.hover.background": "#27272a",
    "primary.active.background": "#3f3f46",
    "danger.background": "#ef4444",
    "danger.foreground": "#ffffff",
    "danger.hover.background": "#dc2626",
    "danger.active.background": "#b91c1c",
    "warning.background": "#f59e0b",
    "warning.foreground": "#ffffff",
    "warning.hover.background": "#d97706",
    "warning.active.background": "#b45309",
    "success.background": "#10b981",
    "success.foreground": "#ffffff",
    "success.hover.background": "#059669",
    "success.active.background": "#047857",
    "sidebar.background": "#fafafa",
    "sidebar.foreground": "#18181b",
    "sidebar.border": "#e4e4e7",
    "sidebar.accent.background": "#f4f4f5",
    "sidebar.accent.foreground": "#09090b",
    "sidebar.primary.background": "#18181b",
    "sidebar.primary.foreground": "#fafafa",
    "list.background": "#ffffff",
    "list.even.background": "#fafafa",
    "list.hover.background": "#f4f4f5",
    "list.active.background": "#e4e4e7",
    "list.active.border": "#18181b",
    "list.head.background": "#f4f4f5",
    "tab.background": "#f4f4f5",
    "tab.active.background": "#ffffff",
    "tab.active.foreground": "#09090b",
    "tab.foreground": "#71717a",
    "tab_bar.background": "#fafafa",
    "tab_bar.segmented.background": "#e4e4e7",
    "table.background": "#ffffff",
    "table.even.background": "#fafafa",
    "table.head.background": "#f4f4f5",
    "table.head.foreground": "#71717a",
    "table.hover.background": "#f4f4f5",
    "table.active.background": "#e4e4e7",
    "table.active.border": "#18181b",
    "table.row.border": "#e4e4e7",
    "popover.background": "#ffffff",
    "popover.foreground": "#09090b",
    "overlay.background": "#00000080",
    "title_bar.background": "#ffffff",
    "title_bar.border": "#e4e4e7",
    "selection.background": "#dbeafe",
    "accent.background": "#f4f4f5",
    "accent.foreground": "#09090b",
    "panel.background": "#f4f4f5",
    "scrollbar.background": "#FFFFFF00",
    "scrollbar.thumb.background": "#d4d4d8"
}

# Update Dark Theme (Zinc)
dark_colors = {
    "background": "#09090b",
    "foreground": "#fafafa",
    "border": "#27272a",
    "ring": "#fafafa",
    "input.border": "#27272a",
    "muted.background": "#18181b",
    "muted.foreground": "#a1a1aa",
    "secondary.background": "#27272a",
    "secondary.foreground": "#fafafa",
    "secondary.hover.background": "#3f3f46",
    "secondary.active.background": "#52525b",
    "primary.background": "#fafafa",
    "primary.foreground": "#09090b",
    "primary.hover.background": "#f4f4f5",
    "primary.active.background": "#e4e4e7",
    "danger.background": "#7f1d1d",
    "danger.foreground": "#fca5a5",
    "danger.hover.background": "#991b1b",
    "danger.active.background": "#b91c1c",
    "warning.background": "#78350f",
    "warning.foreground": "#fcd34d",
    "warning.hover.background": "#92400e",
    "warning.active.background": "#b45309",
    "success.background": "#064e3b",
    "success.foreground": "#6ee7b7",
    "success.hover.background": "#065f46",
    "success.active.background": "#047857",
    "sidebar.background": "#09090b",
    "sidebar.foreground": "#fafafa",
    "sidebar.border": "#27272a",
    "sidebar.accent.background": "#18181b",
    "sidebar.accent.foreground": "#fafafa",
    "sidebar.primary.background": "#fafafa",
    "sidebar.primary.foreground": "#09090b",
    "list.background": "#09090b",
    "list.even.background": "#18181b",
    "list.hover.background": "#27272a",
    "list.active.background": "#3f3f46",
    "list.active.border": "#fafafa",
    "list.head.background": "#18181b",
    "tab.background": "#18181b",
    "tab.active.background": "#09090b",
    "tab.active.foreground": "#fafafa",
    "tab.foreground": "#a1a1aa",
    "tab_bar.background": "#09090b",
    "tab_bar.segmented.background": "#18181b",
    "table.background": "#09090b",
    "table.even.background": "#18181b",
    "table.head.background": "#18181b",
    "table.head.foreground": "#a1a1aa",
    "table.hover.background": "#27272a",
    "table.active.background": "#3f3f46",
    "table.active.border": "#fafafa",
    "table.row.border": "#27272a",
    "popover.background": "#09090b",
    "popover.foreground": "#fafafa",
    "overlay.background": "#000000cc",
    "title_bar.background": "#09090b",
    "title_bar.border": "#27272a",
    "selection.background": "#1e3a8a",
    "accent.background": "#27272a",
    "accent.foreground": "#fafafa",
    "panel.background": "#18181b",
    "scrollbar.background": "#FFFFFF00",
    "scrollbar.thumb.background": "#3f3f46"
}

for theme in data["themes"]:
    if theme["name"] == "Default Light":
        theme["colors"].update(light_colors)
    elif theme["name"] == "macOS Classic Dark":
        theme["name"] = "Modern Dark"
        theme["colors"].update(dark_colors)

with open("crates/ui/src/theme/default-theme.json", "w") as f:
    json.dump(data, f, indent=2)
