[package]
name = "remote_file_editor"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
gpui = { workspace = true}
gpui-component = { workspace = true }
one-core = { workspace = true }
rust-i18n.workspace = true
sftp = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
